"""Kanji content for Phase 13 (Kanji).

The 80 characters below, their readings, and their meanings are drawn from
the widely-used community-compiled JLPT N5 kanji list (the Japan
Foundation/JEES stopped publishing an official kanji list after 2010, so
every study resource — Tanos, JLPTsensei, WaniKani, etc. — works from the
same reverse-engineered consensus set derived from real past exams and
standard kanji dictionaries; character/reading/meaning facts themselves
aren't copyrightable). The `example_word`/`example_reading`/
`example_meaning` fields are original compositions written for this app,
not copied from any source, same as Phase 3's vocabulary/grammar content.
"""

KANJI_N5: list[dict] = [
    {
        "character": "日",
        "onyomi": "ニチ、ジツ",
        "kunyomi": "ひ、-び、-か",
        "meaning": "day, sun, Japan",
        "level": "N5",
        "example_word": "毎日",
        "example_reading": "まいにち",
        "example_meaning": "every day",
    },
    {
        "character": "一",
        "onyomi": "イチ",
        "kunyomi": "ひと(つ)",
        "meaning": "one",
        "level": "N5",
        "example_word": "一人",
        "example_reading": "ひとり",
        "example_meaning": "one person, alone",
    },
    {
        "character": "国",
        "onyomi": "コク",
        "kunyomi": "くに",
        "meaning": "country",
        "level": "N5",
        "example_word": "外国",
        "example_reading": "がいこく",
        "example_meaning": "foreign country",
    },
    {
        "character": "人",
        "onyomi": "ジン、ニン",
        "kunyomi": "ひと",
        "meaning": "person",
        "level": "N5",
        "example_word": "日本人",
        "example_reading": "にほんじん",
        "example_meaning": "Japanese person",
    },
    {
        "character": "年",
        "onyomi": "ネン",
        "kunyomi": "とし",
        "meaning": "year",
        "level": "N5",
        "example_word": "今年",
        "example_reading": "ことし",
        "example_meaning": "this year",
    },
    {
        "character": "大",
        "onyomi": "ダイ、タイ",
        "kunyomi": "おお(きい)",
        "meaning": "large, big",
        "level": "N5",
        "example_word": "大学",
        "example_reading": "だいがく",
        "example_meaning": "university",
    },
    {
        "character": "十",
        "onyomi": "ジュウ",
        "kunyomi": "とお",
        "meaning": "ten",
        "level": "N5",
        "example_word": "十分",
        "example_reading": "じゅっぷん",
        "example_meaning": "ten minutes",
    },
    {
        "character": "二",
        "onyomi": "ニ",
        "kunyomi": "ふた(つ)",
        "meaning": "two",
        "level": "N5",
        "example_word": "二人",
        "example_reading": "ふたり",
        "example_meaning": "two people",
    },
    {
        "character": "本",
        "onyomi": "ホン",
        "kunyomi": "もと",
        "meaning": "book, origin",
        "level": "N5",
        "example_word": "本当",
        "example_reading": "ほんとう",
        "example_meaning": "really, truth",
    },
    {
        "character": "中",
        "onyomi": "チュウ",
        "kunyomi": "なか",
        "meaning": "inside, middle",
        "level": "N5",
        "example_word": "中学校",
        "example_reading": "ちゅうがっこう",
        "example_meaning": "junior high school",
    },
    {
        "character": "長",
        "onyomi": "チョウ",
        "kunyomi": "なが(い)",
        "meaning": "long, chief",
        "level": "N5",
        "example_word": "長い",
        "example_reading": "ながい",
        "example_meaning": "long",
    },
    {
        "character": "出",
        "onyomi": "シュツ",
        "kunyomi": "で(る)、だ(す)",
        "meaning": "exit, leave",
        "level": "N5",
        "example_word": "出口",
        "example_reading": "でぐち",
        "example_meaning": "exit",
    },
    {
        "character": "三",
        "onyomi": "サン",
        "kunyomi": "みっ(つ)",
        "meaning": "three",
        "level": "N5",
        "example_word": "三日",
        "example_reading": "みっか",
        "example_meaning": "the third day, three days",
    },
    {
        "character": "時",
        "onyomi": "ジ",
        "kunyomi": "とき",
        "meaning": "time, hour",
        "level": "N5",
        "example_word": "時間",
        "example_reading": "じかん",
        "example_meaning": "time",
    },
    {
        "character": "行",
        "onyomi": "コウ、ギョウ",
        "kunyomi": "い(く)",
        "meaning": "go",
        "level": "N5",
        "example_word": "旅行",
        "example_reading": "りょこう",
        "example_meaning": "travel",
    },
    {
        "character": "見",
        "onyomi": "ケン",
        "kunyomi": "み(る)",
        "meaning": "see, look",
        "level": "N5",
        "example_word": "見物",
        "example_reading": "けんぶつ",
        "example_meaning": "sightseeing",
    },
    {
        "character": "月",
        "onyomi": "ゲツ、ガツ",
        "kunyomi": "つき",
        "meaning": "month, moon",
        "level": "N5",
        "example_word": "来月",
        "example_reading": "らいげつ",
        "example_meaning": "next month",
    },
    {
        "character": "分",
        "onyomi": "フン、ブン",
        "kunyomi": "わ(ける)",
        "meaning": "part, minute",
        "level": "N5",
        "example_word": "自分",
        "example_reading": "じぶん",
        "example_meaning": "oneself",
    },
    {
        "character": "後",
        "onyomi": "ゴ、コウ",
        "kunyomi": "のち、うし(ろ)",
        "meaning": "behind, after",
        "level": "N5",
        "example_word": "午後",
        "example_reading": "ごご",
        "example_meaning": "afternoon, p.m.",
    },
    {
        "character": "前",
        "onyomi": "ゼン",
        "kunyomi": "まえ",
        "meaning": "before, in front",
        "level": "N5",
        "example_word": "午前",
        "example_reading": "ごぜん",
        "example_meaning": "morning, a.m.",
    },
    {
        "character": "生",
        "onyomi": "セイ",
        "kunyomi": "い(きる)、う(まれる)",
        "meaning": "life, birth",
        "level": "N5",
        "example_word": "学生",
        "example_reading": "がくせい",
        "example_meaning": "student",
    },
    {
        "character": "五",
        "onyomi": "ゴ",
        "kunyomi": "いつ(つ)",
        "meaning": "five",
        "level": "N5",
        "example_word": "五月",
        "example_reading": "ごがつ",
        "example_meaning": "May",
    },
    {
        "character": "間",
        "onyomi": "カン",
        "kunyomi": "あいだ",
        "meaning": "interval, space",
        "level": "N5",
        "example_word": "人間",
        "example_reading": "にんげん",
        "example_meaning": "human being",
    },
    {
        "character": "上",
        "onyomi": "ジョウ",
        "kunyomi": "うえ",
        "meaning": "above, up",
        "level": "N5",
        "example_word": "上手",
        "example_reading": "じょうず",
        "example_meaning": "skillful",
    },
    {
        "character": "東",
        "onyomi": "トウ",
        "kunyomi": "ひがし",
        "meaning": "east",
        "level": "N5",
        "example_word": "東京",
        "example_reading": "とうきょう",
        "example_meaning": "Tokyo",
    },
    {
        "character": "四",
        "onyomi": "シ",
        "kunyomi": "よっ(つ)、よん",
        "meaning": "four",
        "level": "N5",
        "example_word": "四月",
        "example_reading": "しがつ",
        "example_meaning": "April",
    },
    {
        "character": "今",
        "onyomi": "コン",
        "kunyomi": "いま",
        "meaning": "now",
        "level": "N5",
        "example_word": "今日",
        "example_reading": "きょう",
        "example_meaning": "today",
    },
    {
        "character": "金",
        "onyomi": "キン",
        "kunyomi": "かね",
        "meaning": "gold, money",
        "level": "N5",
        "example_word": "お金",
        "example_reading": "おかね",
        "example_meaning": "money",
    },
    {
        "character": "九",
        "onyomi": "キュウ、ク",
        "kunyomi": "ここの(つ)",
        "meaning": "nine",
        "level": "N5",
        "example_word": "九月",
        "example_reading": "くがつ",
        "example_meaning": "September",
    },
    {
        "character": "入",
        "onyomi": "ニュウ",
        "kunyomi": "い(る)、はい(る)",
        "meaning": "enter, insert",
        "level": "N5",
        "example_word": "入り口",
        "example_reading": "いりぐち",
        "example_meaning": "entrance",
    },
    {
        "character": "学",
        "onyomi": "ガク",
        "kunyomi": "まな(ぶ)",
        "meaning": "study, learning",
        "level": "N5",
        "example_word": "学校",
        "example_reading": "がっこう",
        "example_meaning": "school",
    },
    {
        "character": "高",
        "onyomi": "コウ",
        "kunyomi": "たか(い)",
        "meaning": "tall, high, expensive",
        "level": "N5",
        "example_word": "高校",
        "example_reading": "こうこう",
        "example_meaning": "high school",
    },
    {
        "character": "円",
        "onyomi": "エン",
        "kunyomi": "まる(い)",
        "meaning": "circle, yen",
        "level": "N5",
        "example_word": "百円",
        "example_reading": "ひゃくえん",
        "example_meaning": "100 yen",
    },
    {
        "character": "子",
        "onyomi": "シ",
        "kunyomi": "こ",
        "meaning": "child",
        "level": "N5",
        "example_word": "子供",
        "example_reading": "こども",
        "example_meaning": "child",
    },
    {
        "character": "外",
        "onyomi": "ガイ",
        "kunyomi": "そと",
        "meaning": "outside",
        "level": "N5",
        "example_word": "外国人",
        "example_reading": "がいこくじん",
        "example_meaning": "foreigner",
    },
    {
        "character": "八",
        "onyomi": "ハチ",
        "kunyomi": "やっ(つ)",
        "meaning": "eight",
        "level": "N5",
        "example_word": "八月",
        "example_reading": "はちがつ",
        "example_meaning": "August",
    },
    {
        "character": "六",
        "onyomi": "ロク",
        "kunyomi": "むっ(つ)",
        "meaning": "six",
        "level": "N5",
        "example_word": "六月",
        "example_reading": "ろくがつ",
        "example_meaning": "June",
    },
    {
        "character": "下",
        "onyomi": "カ、ゲ",
        "kunyomi": "した",
        "meaning": "below, down",
        "level": "N5",
        "example_word": "下手",
        "example_reading": "へた",
        "example_meaning": "unskillful",
    },
    {
        "character": "来",
        "onyomi": "ライ",
        "kunyomi": "く(る)",
        "meaning": "come",
        "level": "N5",
        "example_word": "来年",
        "example_reading": "らいねん",
        "example_meaning": "next year",
    },
    {
        "character": "気",
        "onyomi": "キ、ケ",
        "kunyomi": "—",
        "meaning": "spirit, mind, air",
        "level": "N5",
        "example_word": "元気",
        "example_reading": "げんき",
        "example_meaning": "healthy, energetic",
    },
    {
        "character": "小",
        "onyomi": "ショウ",
        "kunyomi": "ちい(さい)",
        "meaning": "little, small",
        "level": "N5",
        "example_word": "小学校",
        "example_reading": "しょうがっこう",
        "example_meaning": "elementary school",
    },
    {
        "character": "七",
        "onyomi": "シチ",
        "kunyomi": "なな(つ)",
        "meaning": "seven",
        "level": "N5",
        "example_word": "七月",
        "example_reading": "しちがつ",
        "example_meaning": "July",
    },
    {
        "character": "山",
        "onyomi": "サン",
        "kunyomi": "やま",
        "meaning": "mountain",
        "level": "N5",
        "example_word": "富士山",
        "example_reading": "ふじさん",
        "example_meaning": "Mt. Fuji",
    },
    {
        "character": "話",
        "onyomi": "ワ",
        "kunyomi": "はな(す)",
        "meaning": "talk, story",
        "level": "N5",
        "example_word": "電話",
        "example_reading": "でんわ",
        "example_meaning": "telephone",
    },
    {
        "character": "女",
        "onyomi": "ジョ",
        "kunyomi": "おんな",
        "meaning": "woman, female",
        "level": "N5",
        "example_word": "女の子",
        "example_reading": "おんなのこ",
        "example_meaning": "girl",
    },
    {
        "character": "北",
        "onyomi": "ホク",
        "kunyomi": "きた",
        "meaning": "north",
        "level": "N5",
        "example_word": "北海道",
        "example_reading": "ほっかいどう",
        "example_meaning": "Hokkaido",
    },
    {
        "character": "午",
        "onyomi": "ゴ",
        "kunyomi": "—",
        "meaning": "noon",
        "level": "N5",
        "example_word": "正午",
        "example_reading": "しょうご",
        "example_meaning": "noon",
    },
    {
        "character": "百",
        "onyomi": "ヒャク",
        "kunyomi": "—",
        "meaning": "hundred",
        "level": "N5",
        "example_word": "百人",
        "example_reading": "ひゃくにん",
        "example_meaning": "a hundred people",
    },
    {
        "character": "書",
        "onyomi": "ショ",
        "kunyomi": "か(く)",
        "meaning": "write",
        "level": "N5",
        "example_word": "辞書",
        "example_reading": "じしょ",
        "example_meaning": "dictionary",
    },
    {
        "character": "先",
        "onyomi": "セン",
        "kunyomi": "さき",
        "meaning": "before, ahead",
        "level": "N5",
        "example_word": "先生",
        "example_reading": "せんせい",
        "example_meaning": "teacher",
    },
    {
        "character": "名",
        "onyomi": "メイ",
        "kunyomi": "な",
        "meaning": "name",
        "level": "N5",
        "example_word": "名前",
        "example_reading": "なまえ",
        "example_meaning": "name",
    },
    {
        "character": "川",
        "onyomi": "セン",
        "kunyomi": "かわ",
        "meaning": "river",
        "level": "N5",
        "example_word": "川",
        "example_reading": "かわ",
        "example_meaning": "river",
    },
    {
        "character": "千",
        "onyomi": "セン",
        "kunyomi": "—",
        "meaning": "thousand",
        "level": "N5",
        "example_word": "三千円",
        "example_reading": "さんぜんえん",
        "example_meaning": "3,000 yen",
    },
    {
        "character": "水",
        "onyomi": "スイ",
        "kunyomi": "みず",
        "meaning": "water",
        "level": "N5",
        "example_word": "水曜日",
        "example_reading": "すいようび",
        "example_meaning": "Wednesday",
    },
    {
        "character": "半",
        "onyomi": "ハン",
        "kunyomi": "なか(ば)",
        "meaning": "half",
        "level": "N5",
        "example_word": "半分",
        "example_reading": "はんぶん",
        "example_meaning": "half",
    },
    {
        "character": "男",
        "onyomi": "ダン、ナン",
        "kunyomi": "おとこ",
        "meaning": "male, man",
        "level": "N5",
        "example_word": "男の人",
        "example_reading": "おとこのひと",
        "example_meaning": "man",
    },
    {
        "character": "西",
        "onyomi": "セイ",
        "kunyomi": "にし",
        "meaning": "west",
        "level": "N5",
        "example_word": "西口",
        "example_reading": "にしぐち",
        "example_meaning": "west exit",
    },
    {
        "character": "電",
        "onyomi": "デン",
        "kunyomi": "—",
        "meaning": "electricity",
        "level": "N5",
        "example_word": "電車",
        "example_reading": "でんしゃ",
        "example_meaning": "train",
    },
    {
        "character": "校",
        "onyomi": "コウ",
        "kunyomi": "—",
        "meaning": "school",
        "level": "N5",
        "example_word": "校長",
        "example_reading": "こうちょう",
        "example_meaning": "principal",
    },
    {
        "character": "語",
        "onyomi": "ゴ",
        "kunyomi": "かた(る)",
        "meaning": "word, language",
        "level": "N5",
        "example_word": "日本語",
        "example_reading": "にほんご",
        "example_meaning": "Japanese language",
    },
    {
        "character": "土",
        "onyomi": "ド、ト",
        "kunyomi": "つち",
        "meaning": "soil, earth",
        "level": "N5",
        "example_word": "土曜日",
        "example_reading": "どようび",
        "example_meaning": "Saturday",
    },
    {
        "character": "木",
        "onyomi": "モク、ボク",
        "kunyomi": "き",
        "meaning": "tree, wood",
        "level": "N5",
        "example_word": "木曜日",
        "example_reading": "もくようび",
        "example_meaning": "Thursday",
    },
    {
        "character": "聞",
        "onyomi": "ブン、モン",
        "kunyomi": "き(く)",
        "meaning": "hear, listen, ask",
        "level": "N5",
        "example_word": "新聞",
        "example_reading": "しんぶん",
        "example_meaning": "newspaper",
    },
    {
        "character": "食",
        "onyomi": "ショク",
        "kunyomi": "た(べる)",
        "meaning": "eat, food",
        "level": "N5",
        "example_word": "食べ物",
        "example_reading": "たべもの",
        "example_meaning": "food",
    },
    {
        "character": "車",
        "onyomi": "シャ",
        "kunyomi": "くるま",
        "meaning": "car, wheel",
        "level": "N5",
        "example_word": "自動車",
        "example_reading": "じどうしゃ",
        "example_meaning": "automobile",
    },
    {
        "character": "何",
        "onyomi": "カ",
        "kunyomi": "なに、なん",
        "meaning": "what",
        "level": "N5",
        "example_word": "何時",
        "example_reading": "なんじ",
        "example_meaning": "what time",
    },
    {
        "character": "南",
        "onyomi": "ナン",
        "kunyomi": "みなみ",
        "meaning": "south",
        "level": "N5",
        "example_word": "南口",
        "example_reading": "みなみぐち",
        "example_meaning": "south exit",
    },
    {
        "character": "万",
        "onyomi": "マン",
        "kunyomi": "—",
        "meaning": "ten thousand",
        "level": "N5",
        "example_word": "一万円",
        "example_reading": "いちまんえん",
        "example_meaning": "10,000 yen",
    },
    {
        "character": "毎",
        "onyomi": "マイ",
        "kunyomi": "—",
        "meaning": "every",
        "level": "N5",
        "example_word": "毎週",
        "example_reading": "まいしゅう",
        "example_meaning": "every week",
    },
    {
        "character": "白",
        "onyomi": "ハク",
        "kunyomi": "しろ(い)",
        "meaning": "white",
        "level": "N5",
        "example_word": "白い",
        "example_reading": "しろい",
        "example_meaning": "white",
    },
    {
        "character": "天",
        "onyomi": "テン",
        "kunyomi": "—",
        "meaning": "heavens, sky",
        "level": "N5",
        "example_word": "天気",
        "example_reading": "てんき",
        "example_meaning": "weather",
    },
    {
        "character": "母",
        "onyomi": "ボ",
        "kunyomi": "はは",
        "meaning": "mother",
        "level": "N5",
        "example_word": "お母さん",
        "example_reading": "おかあさん",
        "example_meaning": "mother",
    },
    {
        "character": "火",
        "onyomi": "カ",
        "kunyomi": "ひ",
        "meaning": "fire",
        "level": "N5",
        "example_word": "火曜日",
        "example_reading": "かようび",
        "example_meaning": "Tuesday",
    },
    {
        "character": "右",
        "onyomi": "ウ、ユウ",
        "kunyomi": "みぎ",
        "meaning": "right (direction)",
        "level": "N5",
        "example_word": "右手",
        "example_reading": "みぎて",
        "example_meaning": "right hand",
    },
    {
        "character": "読",
        "onyomi": "ドク",
        "kunyomi": "よ(む)",
        "meaning": "read",
        "level": "N5",
        "example_word": "読書",
        "example_reading": "どくしょ",
        "example_meaning": "reading (books)",
    },
    {
        "character": "友",
        "onyomi": "ユウ",
        "kunyomi": "とも",
        "meaning": "friend",
        "level": "N5",
        "example_word": "友達",
        "example_reading": "ともだち",
        "example_meaning": "friend",
    },
    {
        "character": "左",
        "onyomi": "サ",
        "kunyomi": "ひだり",
        "meaning": "left",
        "level": "N5",
        "example_word": "左手",
        "example_reading": "ひだりて",
        "example_meaning": "left hand",
    },
    {
        "character": "休",
        "onyomi": "キュウ",
        "kunyomi": "やす(む)",
        "meaning": "rest, day off",
        "level": "N5",
        "example_word": "休み",
        "example_reading": "やすみ",
        "example_meaning": "rest, vacation",
    },
    {
        "character": "父",
        "onyomi": "フ",
        "kunyomi": "ちち",
        "meaning": "father",
        "level": "N5",
        "example_word": "お父さん",
        "example_reading": "おとうさん",
        "example_meaning": "father",
    },
    {
        "character": "雨",
        "onyomi": "ウ",
        "kunyomi": "あめ",
        "meaning": "rain",
        "level": "N5",
        "example_word": "雨天",
        "example_reading": "うてん",
        "example_meaning": "rainy weather",
    },
]
