"""Starter vocabulary + N5 grammar content, originally written for JapJap
(no sentence here is copied from any textbook, app, or past exam).

The grammar list (Phase 13) is a curated subset of the ~80-point N5
grammar scope reverse-engineered by the JLPT study community from real
past exams (the Japan Foundation/JEES stopped publishing an official list
after 2010 — see docs/PROJECT_STATE.md's Phase 13 section for sourcing
notes). Curated, not exhaustive: entries that are grammatical categories
rather than fill-in-the-blank patterns (e.g. "i-adjectives" as a listing)
don't fit this app's sentence-completion format and were left out.
Vocabulary depth (this app's 12 items vs. the ~800-word N5 scope) is
Phase 14's job.
"""

VOCABULARY_N5: list[dict] = [
    {
        "term": "食べる",
        "reading": "たべる",
        "meaning": "to eat",
        "level": "N5",
        "example_sentence": "朝ごはんを食べます。",
        "example_translation": "I eat breakfast.",
    },
    {
        "term": "飲む",
        "reading": "のむ",
        "meaning": "to drink",
        "level": "N5",
        "example_sentence": "水を飲みます。",
        "example_translation": "I drink water.",
    },
    {
        "term": "見る",
        "reading": "みる",
        "meaning": "to see, to watch",
        "level": "N5",
        "example_sentence": "テレビを見ます。",
        "example_translation": "I watch TV.",
    },
    {
        "term": "行く",
        "reading": "いく",
        "meaning": "to go",
        "level": "N5",
        "example_sentence": "学校に行きます。",
        "example_translation": "I go to school.",
    },
    {
        "term": "来る",
        "reading": "くる",
        "meaning": "to come",
        "level": "N5",
        "example_sentence": "友達が来ます。",
        "example_translation": "My friend is coming.",
    },
    {
        "term": "する",
        "reading": "する",
        "meaning": "to do",
        "level": "N5",
        "example_sentence": "勉強をします。",
        "example_translation": "I study.",
    },
    {
        "term": "大きい",
        "reading": "おおきい",
        "meaning": "big",
        "level": "N5",
        "example_sentence": "大きい犬です。",
        "example_translation": "It is a big dog.",
    },
    {
        "term": "小さい",
        "reading": "ちいさい",
        "meaning": "small",
        "level": "N5",
        "example_sentence": "小さい部屋です。",
        "example_translation": "It is a small room.",
    },
    {
        "term": "学校",
        "reading": "がっこう",
        "meaning": "school",
        "level": "N5",
        "example_sentence": "学校は九時からです。",
        "example_translation": "School starts at nine.",
    },
    {
        "term": "友達",
        "reading": "ともだち",
        "meaning": "friend",
        "level": "N5",
        "example_sentence": "友達と話します。",
        "example_translation": "I talk with my friend.",
    },
    {
        "term": "水",
        "reading": "みず",
        "meaning": "water",
        "level": "N5",
        "example_sentence": "水がほしいです。",
        "example_translation": "I want water.",
    },
    {
        "term": "本",
        "reading": "ほん",
        "meaning": "book",
        "level": "N5",
        "example_sentence": "本を読みます。",
        "example_translation": "I read a book.",
    },
]

GRAMMAR_N5: list[dict] = [
    {
        "key": "particle-wo",
        "title": "Particle を (object marker)",
        "level": "N5",
        "explanation": "を marks the direct object of a verb.",
        "example_sentence": "水___飲みます。",
        "example_translation": "I drink water.",
        "answer": "を",
    },
    {
        "key": "particle-ga",
        "title": "Particle が (subject marker)",
        "level": "N5",
        "explanation": "が marks the grammatical subject, often introducing new information.",
        "example_sentence": "猫___います。",
        "example_translation": "There is a cat.",
        "answer": "が",
    },
    {
        "key": "particle-ni",
        "title": "Particle に (direction/time marker)",
        "level": "N5",
        "explanation": "に marks a destination, a point in time, or an indirect object.",
        "example_sentence": "学校___行きます。",
        "example_translation": "I go to school.",
        "answer": "に",
    },
    {
        "key": "particle-de",
        "title": "Particle で (location of an action)",
        "level": "N5",
        "explanation": "で marks the place where an action happens.",
        "example_sentence": "図書館___勉強します。",
        "example_translation": "I study at the library.",
        "answer": "で",
    },
    {
        "key": "particle-ha",
        "title": "Particle は (topic marker)",
        "level": "N5",
        "explanation": "は marks the topic of the sentence.",
        "example_sentence": "わたし___学生です。",
        "example_translation": "I am a student.",
        "answer": "は",
    },
    {
        "key": "past-tense-deshita",
        "title": "Past tense です → でした",
        "level": "N5",
        "explanation": "でした is the polite past tense of です.",
        "example_sentence": "昨日は晴れ___。",
        "example_translation": "It was sunny yesterday.",
        "answer": "でした",
    },
    {
        "key": "negative-verb-masen",
        "title": "Negative verb ~ません",
        "level": "N5",
        "explanation": "ません makes a polite verb negative.",
        "example_sentence": "肉を食べ___。",
        "example_translation": "I do not eat meat.",
        "answer": "ません",
    },
    {
        "key": "te-form-request",
        "title": "て-form request (~てください)",
        "level": "N5",
        "explanation": "てください is used to politely ask someone to do something.",
        "example_sentence": "ここに座っ___ください。",
        "example_translation": "Please sit here.",
        "answer": "て",
    },
    {
        "key": "particle-mo",
        "title": "Particle も (also, too)",
        "level": "N5",
        "explanation": "も replaces は/が to mean 'also' or 'too'.",
        "example_sentence": "私___学生です。",
        "example_translation": "I am also a student.",
        "answer": "も",
    },
    {
        "key": "particle-to",
        "title": "Particle と (and, with)",
        "level": "N5",
        "explanation": "と connects nouns ('and') or marks who an action is done with.",
        "example_sentence": "友達___公園に行きます。",
        "example_translation": "I go to the park with my friend.",
        "answer": "と",
    },
    {
        "key": "kara-because",
        "title": "から (because, since)",
        "level": "N5",
        "explanation": "から attaches to a plain-form clause to give a reason.",
        "example_sentence": "疲れた___、早く寝ます。",
        "example_translation": "Because I'm tired, I'll sleep early.",
        "answer": "から",
    },
    {
        "key": "made-until",
        "title": "まで (until)",
        "level": "N5",
        "explanation": "まで marks the end point of a time or place.",
        "example_sentence": "九時___働きます。",
        "example_translation": "I work until nine o'clock.",
        "answer": "まで",
    },
    {
        "key": "particle-ya",
        "title": "Particle や (and, among other things)",
        "level": "N5",
        "explanation": (
            "や lists a few examples from a longer, unstated list "
            "(unlike と, which lists everything)."
        ),
        "example_sentence": "机の上に本___ノートがあります。",
        "example_translation": "There are things like books and notebooks on the desk.",
        "answer": "や",
    },
    {
        "key": "particle-ka-question",
        "title": "Particle か (question marker)",
        "level": "N5",
        "explanation": "か at the end of a sentence turns it into a question.",
        "example_sentence": "これはあなたの傘です___。",
        "example_translation": "Is this your umbrella?",
        "answer": "か",
    },
    {
        "key": "invitation-masenka",
        "title": "~ませんか (won't you...?)",
        "level": "N5",
        "explanation": "~ませんか politely invites someone to do something together.",
        "example_sentence": "一緒に映画を見___。",
        "example_translation": "Won't you watch a movie together?",
        "answer": "ませんか",
    },
    {
        "key": "lets-mashou",
        "title": "~ましょう (let's...)",
        "level": "N5",
        "explanation": "~ましょう proposes doing something together.",
        "example_sentence": "そろそろ帰り___。",
        "example_translation": "Let's go home soon.",
        "answer": "ましょう",
    },
    {
        "key": "te-form-permission",
        "title": "~てもいいですか (may I...?)",
        "level": "N5",
        "explanation": "~てもいいですか asks for permission to do something.",
        "example_sentence": "ここに座っ___か。",
        "example_translation": "May I sit here?",
        "answer": "てもいいです",
    },
    {
        "key": "te-form-prohibition",
        "title": "~てはいけません (must not)",
        "level": "N5",
        "explanation": "~てはいけません states that an action is forbidden.",
        "example_sentence": "ここで写真を撮っ___。",
        "example_translation": "You must not take photos here.",
        "answer": "てはいけません",
    },
    {
        "key": "naide-kudasai",
        "title": "~ないでください (please don't)",
        "level": "N5",
        "explanation": "~ないでください politely asks someone not to do something.",
        "example_sentence": "教室で食べ___。",
        "example_translation": "Please don't eat in the classroom.",
        "answer": "ないでください",
    },
    {
        "key": "verb-tai",
        "title": "~たい (want to)",
        "level": "N5",
        "explanation": (
            "~たい attaches to a verb's stem to express the speaker's own desire to do it."
        ),
        "example_sentence": "日本に行き___です。",
        "example_translation": "I want to go to Japan.",
        "answer": "たい",
    },
    {
        "key": "te-form-progressive",
        "title": "~ています (ongoing action)",
        "level": "N5",
        "explanation": "~ています describes an action in progress right now.",
        "example_sentence": "今、雨が降っ___。",
        "example_translation": "It is raining now.",
        "answer": "ています",
    },
    {
        "key": "te-form-after",
        "title": "~てから (after doing)",
        "level": "N5",
        "explanation": (
            "~てから sequences two actions: the first finishes before the second starts."
        ),
        "example_sentence": "手を洗っ___、食べます。",
        "example_translation": "After washing my hands, I eat.",
        "answer": "てから",
    },
    {
        "key": "ta-koto-ga-aru",
        "title": "~たことがあります (have done before)",
        "level": "N5",
        "explanation": "~たことがあります describes a past experience.",
        "example_sentence": "沖縄へ行っ___。",
        "example_translation": "I have been to Okinawa before.",
        "answer": "たことがあります",
    },
    {
        "key": "node-because",
        "title": "ので (because, since)",
        "level": "N5",
        "explanation": "ので gives a reason, softer and more objective-sounding than から.",
        "example_sentence": "頭が痛い___、休みます。",
        "example_translation": "Because I have a headache, I'll rest.",
        "answer": "ので",
    },
    {
        "key": "verb-sugiru",
        "title": "~すぎる (too much)",
        "level": "N5",
        "explanation": "~すぎる attaches to a verb/adjective stem to mean 'excessively'.",
        "example_sentence": "このコーヒーは熱___。",
        "example_translation": "This coffee is too hot.",
        "answer": "すぎます",
    },
    {
        "key": "deshou-probably",
        "title": "~でしょう (probably)",
        "level": "N5",
        "explanation": "~でしょう softens a statement into a probable guess.",
        "example_sentence": "明日は晴れる___。",
        "example_translation": "It will probably be sunny tomorrow.",
        "answer": "でしょう",
    },
    {
        "key": "ndesu-explanatory",
        "title": "~んですか (explanatory question)",
        "level": "N5",
        "explanation": "~んですか asks for an explanation or shows the speaker noticed something.",
        "example_sentence": "どうして遅れた___か。",
        "example_translation": "Why are you late?",
        "answer": "んです",
    },
    {
        "key": "tsumori-intend",
        "title": "~つもりです (intend to)",
        "level": "N5",
        "explanation": "~つもりです states a plan or intention.",
        "example_sentence": "来年、留学する___です。",
        "example_translation": "I intend to study abroad next year.",
        "answer": "つもり",
    },
    {
        "key": "hou-ga-ii",
        "title": "~ほうがいいです (had better)",
        "level": "N5",
        "explanation": "~ほうがいいです gives advice, usually after a plain-past verb.",
        "example_sentence": "早く病院へ行った___です。",
        "example_translation": "You had better go to the hospital soon.",
        "answer": "ほうがいい",
    },
    {
        "key": "naku-temo-ii",
        "title": "~なくてもいいです (don't have to)",
        "level": "N5",
        "explanation": "~なくてもいいです says an action isn't necessary.",
        "example_sentence": "明日は仕事に行か___です。",
        "example_translation": "I don't have to go to work tomorrow.",
        "answer": "なくてもいい",
    },
    {
        "key": "nakereba-naranai",
        "title": "~なければなりません (must)",
        "level": "N5",
        "explanation": "~なければなりません states an obligation.",
        "example_sentence": "宿題をし___。",
        "example_translation": "I must do my homework.",
        "answer": "なければなりません",
    },
    {
        "key": "hoshii-want",
        "title": "~がほしいです (want something)",
        "level": "N5",
        "explanation": "ほしい is an い-adjective expressing a desire for a thing (not an action).",
        "example_sentence": "新しい靴が___です。",
        "example_translation": "I want new shoes.",
        "answer": "ほしい",
    },
    {
        "key": "yori-comparison",
        "title": "AはBより (A is more ~ than B)",
        "level": "N5",
        "explanation": "より marks the thing being compared against.",
        "example_sentence": "新幹線は電車___速いです。",
        "example_translation": "The shinkansen is faster than the train.",
        "answer": "より",
    },
    {
        "key": "ichiban-most",
        "title": "~の中で一番 (the most, out of a group)",
        "level": "N5",
        "explanation": "一番 means 'most/best' when comparing within a group introduced by の中で.",
        "example_sentence": "果物の中で、りんごが___好きです。",
        "example_translation": "Among fruits, I like apples the most.",
        "answer": "一番",
    },
    {
        "key": "ni-suru-decide",
        "title": "~にします (decide on)",
        "level": "N5",
        "explanation": "~にします states a choice/decision among options.",
        "example_sentence": "飲み物はコーヒーに___。",
        "example_translation": "I'll have coffee for my drink.",
        "answer": "します",
    },
    {
        "key": "ni-iku-purpose",
        "title": "~に行きます (go in order to)",
        "level": "N5",
        "explanation": "A verb stem + に行きます expresses going somewhere to do that action.",
        "example_sentence": "映画を見に___。",
        "example_translation": "I'm going to see a movie.",
        "answer": "行きます",
    },
    {
        "key": "no-ga-suki",
        "title": "~のが好きです (like doing)",
        "level": "N5",
        "explanation": "の turns a verb phrase into a noun so 好き/上手/下手 can describe it.",
        "example_sentence": "私は歌う___好きです。",
        "example_translation": "I like singing.",
        "answer": "の",
    },
    {
        "key": "ni-naru-become",
        "title": "~になりました (became)",
        "level": "N5",
        "explanation": "な-adjective/noun + になる describes a change of state.",
        "example_sentence": "日本語が上手___。",
        "example_translation": "My Japanese became skillful.",
        "answer": "になりました",
    },
]
