"""Starter vocabulary + N5 grammar content, originally written for JapJap
(no sentence here is copied from any textbook, app, or past exam).

The grammar list (Phase 13) is a curated subset of the ~80-point N5
grammar scope reverse-engineered by the JLPT study community from real
past exams (the Japan Foundation/JEES stopped publishing an official list
after 2010 — see docs/PROJECT_STATE.md's Phase 13 section for sourcing
notes). Curated, not exhaustive: entries that are grammatical categories
rather than fill-in-the-blank patterns (e.g. "i-adjectives" as a listing)
don't fit this app's sentence-completion format and were left out.

The vocabulary list (Phase 14) is a curated selection from the same kind
of community-compiled ~800-word N5 scope reference (not the full list —
see docs/PROJECT_STATE.md's Phase 14 section for how much and why).
"""

VOCABULARY_N5: list[dict] = [
    {
        "term": "食べる",
        "reading": "たべる",
        "meaning": "to eat",
        "level": "N5",
        "example_sentence": "朝ごはんを食べます。",
        "example_translation": "I eat breakfast.",
    },
    {
        "term": "飲む",
        "reading": "のむ",
        "meaning": "to drink",
        "level": "N5",
        "example_sentence": "水を飲みます。",
        "example_translation": "I drink water.",
    },
    {
        "term": "見る",
        "reading": "みる",
        "meaning": "to see, to watch",
        "level": "N5",
        "example_sentence": "テレビを見ます。",
        "example_translation": "I watch TV.",
    },
    {
        "term": "行く",
        "reading": "いく",
        "meaning": "to go",
        "level": "N5",
        "example_sentence": "学校に行きます。",
        "example_translation": "I go to school.",
    },
    {
        "term": "来る",
        "reading": "くる",
        "meaning": "to come",
        "level": "N5",
        "example_sentence": "友達が来ます。",
        "example_translation": "My friend is coming.",
    },
    {
        "term": "する",
        "reading": "する",
        "meaning": "to do",
        "level": "N5",
        "example_sentence": "勉強をします。",
        "example_translation": "I study.",
    },
    {
        "term": "大きい",
        "reading": "おおきい",
        "meaning": "big",
        "level": "N5",
        "example_sentence": "大きい犬です。",
        "example_translation": "It is a big dog.",
    },
    {
        "term": "小さい",
        "reading": "ちいさい",
        "meaning": "small",
        "level": "N5",
        "example_sentence": "小さい部屋です。",
        "example_translation": "It is a small room.",
    },
    {
        "term": "学校",
        "reading": "がっこう",
        "meaning": "school",
        "level": "N5",
        "example_sentence": "学校は九時からです。",
        "example_translation": "School starts at nine.",
    },
    {
        "term": "友達",
        "reading": "ともだち",
        "meaning": "friend",
        "level": "N5",
        "example_sentence": "友達と話します。",
        "example_translation": "I talk with my friend.",
    },
    {
        "term": "水",
        "reading": "みず",
        "meaning": "water",
        "level": "N5",
        "example_sentence": "水がほしいです。",
        "example_translation": "I want water.",
    },
    {
        "term": "本",
        "reading": "ほん",
        "meaning": "book",
        "level": "N5",
        "example_sentence": "本を読みます。",
        "example_translation": "I read a book.",
    },
    {
        "term": "明日",
        "reading": "あした",
        "meaning": "tomorrow",
        "level": "N5",
        "example_sentence": "明日は忙しいです。",
        "example_translation": "Tomorrow I am busy.",
    },
    {
        "term": "遊ぶ",
        "reading": "あそぶ",
        "meaning": "to play",
        "level": "N5",
        "example_sentence": "公園で遊びます。",
        "example_translation": "I play in the park.",
    },
    {
        "term": "駅",
        "reading": "えき",
        "meaning": "station",
        "level": "N5",
        "example_sentence": "駅まで歩きます。",
        "example_translation": "I walk to the station.",
    },
    {
        "term": "危ない",
        "reading": "あぶない",
        "meaning": "dangerous",
        "level": "N5",
        "example_sentence": "この道は危ないです。",
        "example_translation": "This road is dangerous.",
    },
    {
        "term": "明るい",
        "reading": "あかるい",
        "meaning": "bright",
        "level": "N5",
        "example_sentence": "部屋が明るいです。",
        "example_translation": "The room is bright.",
    },
    {
        "term": "開ける",
        "reading": "あける",
        "meaning": "to open (something)",
        "level": "N5",
        "example_sentence": "窓を開けます。",
        "example_translation": "I open the window.",
    },
    {
        "term": "秋",
        "reading": "あき",
        "meaning": "autumn",
        "level": "N5",
        "example_sentence": "秋は涼しいです。",
        "example_translation": "Autumn is cool.",
    },
    {
        "term": "甘い",
        "reading": "あまい",
        "meaning": "sweet",
        "level": "N5",
        "example_sentence": "このケーキは甘いです。",
        "example_translation": "This cake is sweet.",
    },
    {
        "term": "雨",
        "reading": "あめ",
        "meaning": "rain",
        "level": "N5",
        "example_sentence": "今日は雨です。",
        "example_translation": "It is rainy today.",
    },
    {
        "term": "姉",
        "reading": "あね",
        "meaning": "older sister",
        "level": "N5",
        "example_sentence": "姉は先生です。",
        "example_translation": "My older sister is a teacher.",
    },
    {
        "term": "兄",
        "reading": "あに",
        "meaning": "older brother",
        "level": "N5",
        "example_sentence": "兄は学生です。",
        "example_translation": "My older brother is a student.",
    },
    {
        "term": "忙しい",
        "reading": "いそがしい",
        "meaning": "busy",
        "level": "N5",
        "example_sentence": "今週は忙しいです。",
        "example_translation": "This week is busy.",
    },
    {
        "term": "痛い",
        "reading": "いたい",
        "meaning": "painful",
        "level": "N5",
        "example_sentence": "頭が痛いです。",
        "example_translation": "My head hurts.",
    },
    {
        "term": "一緒",
        "reading": "いっしょ",
        "meaning": "together",
        "level": "N5",
        "example_sentence": "一緒に行きましょう。",
        "example_translation": "Let's go together.",
    },
    {
        "term": "椅子",
        "reading": "いす",
        "meaning": "chair",
        "level": "N5",
        "example_sentence": "椅子に座ります。",
        "example_translation": "I sit on the chair.",
    },
    {
        "term": "犬",
        "reading": "いぬ",
        "meaning": "dog",
        "level": "N5",
        "example_sentence": "犬が好きです。",
        "example_translation": "I like dogs.",
    },
    {
        "term": "妹",
        "reading": "いもうと",
        "meaning": "younger sister",
        "level": "N5",
        "example_sentence": "妹は小さいです。",
        "example_translation": "My younger sister is small.",
    },
    {
        "term": "意味",
        "reading": "いみ",
        "meaning": "meaning",
        "level": "N5",
        "example_sentence": "この言葉の意味が分かりません。",
        "example_translation": "I don't understand the meaning of this word.",
    },
    {
        "term": "色",
        "reading": "いろ",
        "meaning": "color",
        "level": "N5",
        "example_sentence": "好きな色は青です。",
        "example_translation": "My favorite color is blue.",
    },
    {
        "term": "医者",
        "reading": "いしゃ",
        "meaning": "doctor",
        "level": "N5",
        "example_sentence": "父は医者です。",
        "example_translation": "My father is a doctor.",
    },
    {
        "term": "言う",
        "reading": "いう",
        "meaning": "to say",
        "level": "N5",
        "example_sentence": "名前を言ってください。",
        "example_translation": "Please say your name.",
    },
    {
        "term": "要る",
        "reading": "いる",
        "meaning": "to need",
        "level": "N5",
        "example_sentence": "お金が要ります。",
        "example_translation": "I need money.",
    },
    {
        "term": "居る",
        "reading": "いる",
        "meaning": "to be (for people/animals)",
        "level": "N5",
        "example_sentence": "友達は今、部屋にいます。",
        "example_translation": "My friend is in the room now.",
    },
    {
        "term": "自分",
        "reading": "じぶん",
        "meaning": "oneself",
        "level": "N5",
        "example_sentence": "自分で作りました。",
        "example_translation": "I made it myself.",
    },
    {
        "term": "時間",
        "reading": "じかん",
        "meaning": "time",
        "level": "N5",
        "example_sentence": "時間がありません。",
        "example_translation": "I don't have time.",
    },
    {
        "term": "上手",
        "reading": "じょうず",
        "meaning": "skillful",
        "level": "N5",
        "example_sentence": "料理が上手です。",
        "example_translation": "I am good at cooking.",
    },
    {
        "term": "下手",
        "reading": "へた",
        "meaning": "unskillful",
        "level": "N5",
        "example_sentence": "歌が下手です。",
        "example_translation": "I am bad at singing.",
    },
    {
        "term": "家族",
        "reading": "かぞく",
        "meaning": "family",
        "level": "N5",
        "example_sentence": "家族と旅行します。",
        "example_translation": "I travel with my family.",
    },
    {
        "term": "帰る",
        "reading": "かえる",
        "meaning": "to go home",
        "level": "N5",
        "example_sentence": "六時に家に帰ります。",
        "example_translation": "I go home at six o'clock.",
    },
    {
        "term": "買う",
        "reading": "かう",
        "meaning": "to buy",
        "level": "N5",
        "example_sentence": "新しい靴を買います。",
        "example_translation": "I buy new shoes.",
    },
    {
        "term": "買い物",
        "reading": "かいもの",
        "meaning": "shopping",
        "level": "N5",
        "example_sentence": "週末に買い物をします。",
        "example_translation": "I go shopping on the weekend.",
    },
    {
        "term": "書く",
        "reading": "かく",
        "meaning": "to write",
        "level": "N5",
        "example_sentence": "手紙を書きます。",
        "example_translation": "I write a letter.",
    },
    {
        "term": "傘",
        "reading": "かさ",
        "meaning": "umbrella",
        "level": "N5",
        "example_sentence": "傘を持っています。",
        "example_translation": "I have an umbrella.",
    },
    {
        "term": "火曜日",
        "reading": "かようび",
        "meaning": "Tuesday",
        "level": "N5",
        "example_sentence": "火曜日に会いましょう。",
        "example_translation": "Let's meet on Tuesday.",
    },
    {
        "term": "借りる",
        "reading": "かりる",
        "meaning": "to borrow",
        "level": "N5",
        "example_sentence": "図書館で本を借ります。",
        "example_translation": "I borrow a book at the library.",
    },
    {
        "term": "軽い",
        "reading": "かるい",
        "meaning": "light (in weight)",
        "level": "N5",
        "example_sentence": "このかばんは軽いです。",
        "example_translation": "This bag is light.",
    },
    {
        "term": "可愛い",
        "reading": "かわいい",
        "meaning": "cute",
        "level": "N5",
        "example_sentence": "この猫は可愛いです。",
        "example_translation": "This cat is cute.",
    },
    {
        "term": "川",
        "reading": "かわ",
        "meaning": "river",
        "level": "N5",
        "example_sentence": "川で泳ぎます。",
        "example_translation": "I swim in the river.",
    },
    {
        "term": "聞く",
        "reading": "きく",
        "meaning": "to listen, to ask",
        "level": "N5",
        "example_sentence": "音楽を聞きます。",
        "example_translation": "I listen to music.",
    },
    {
        "term": "昨日",
        "reading": "きのう",
        "meaning": "yesterday",
        "level": "N5",
        "example_sentence": "昨日は暑かったです。",
        "example_translation": "Yesterday was hot.",
    },
    {
        "term": "切符",
        "reading": "きっぷ",
        "meaning": "ticket",
        "level": "N5",
        "example_sentence": "切符を買います。",
        "example_translation": "I buy a ticket.",
    },
    {
        "term": "嫌い",
        "reading": "きらい",
        "meaning": "to dislike",
        "level": "N5",
        "example_sentence": "納豆が嫌いです。",
        "example_translation": "I dislike natto.",
    },
    {
        "term": "綺麗",
        "reading": "きれい",
        "meaning": "pretty, clean",
        "level": "N5",
        "example_sentence": "この部屋は綺麗です。",
        "example_translation": "This room is clean.",
    },
    {
        "term": "切る",
        "reading": "きる",
        "meaning": "to cut",
        "level": "N5",
        "example_sentence": "野菜を切ります。",
        "example_translation": "I cut vegetables.",
    },
    {
        "term": "着る",
        "reading": "きる",
        "meaning": "to wear (a top)",
        "level": "N5",
        "example_sentence": "コートを着ます。",
        "example_translation": "I wear a coat.",
    },
    {
        "term": "汚い",
        "reading": "きたない",
        "meaning": "dirty",
        "level": "N5",
        "example_sentence": "この部屋は汚いです。",
        "example_translation": "This room is dirty.",
    },
    {
        "term": "銀行",
        "reading": "ぎんこう",
        "meaning": "bank",
        "level": "N5",
        "example_sentence": "銀行に行きます。",
        "example_translation": "I go to the bank.",
    },
    {
        "term": "玄関",
        "reading": "げんかん",
        "meaning": "entrance (of a house)",
        "level": "N5",
        "example_sentence": "玄関で靴を脱ぎます。",
        "example_translation": "I take off my shoes at the entrance.",
    },
    {
        "term": "元気",
        "reading": "げんき",
        "meaning": "energetic, healthy",
        "level": "N5",
        "example_sentence": "毎日元気です。",
        "example_translation": "I am energetic every day.",
    },
    {
        "term": "月曜日",
        "reading": "げつようび",
        "meaning": "Monday",
        "level": "N5",
        "example_sentence": "月曜日から仕事です。",
        "example_translation": "Work starts from Monday.",
    },
    {
        "term": "ご飯",
        "reading": "ごはん",
        "meaning": "cooked rice, a meal",
        "level": "N5",
        "example_sentence": "ご飯を食べます。",
        "example_translation": "I eat a meal.",
    },
    {
        "term": "午後",
        "reading": "ごご",
        "meaning": "afternoon",
        "level": "N5",
        "example_sentence": "午後に勉強します。",
        "example_translation": "I study in the afternoon.",
    },
    {
        "term": "午前",
        "reading": "ごぜん",
        "meaning": "morning",
        "level": "N5",
        "example_sentence": "午前九時に起きます。",
        "example_translation": "I wake up at nine in the morning.",
    },
    {
        "term": "牛肉",
        "reading": "ぎゅうにく",
        "meaning": "beef",
        "level": "N5",
        "example_sentence": "牛肉を食べません。",
        "example_translation": "I don't eat beef.",
    },
    {
        "term": "牛乳",
        "reading": "ぎゅうにゅう",
        "meaning": "milk",
        "level": "N5",
        "example_sentence": "牛乳を飲みます。",
        "example_translation": "I drink milk.",
    },
    {
        "term": "歯",
        "reading": "は",
        "meaning": "tooth",
        "level": "N5",
        "example_sentence": "歯を磨きます。",
        "example_translation": "I brush my teeth.",
    },
    {
        "term": "母",
        "reading": "はは",
        "meaning": "mother",
        "level": "N5",
        "example_sentence": "母は料理が上手です。",
        "example_translation": "My mother is good at cooking.",
    },
    {
        "term": "入る",
        "reading": "はいる",
        "meaning": "to enter",
        "level": "N5",
        "example_sentence": "部屋に入ります。",
        "example_translation": "I enter the room.",
    },
    {
        "term": "始まる",
        "reading": "はじまる",
        "meaning": "to begin",
        "level": "N5",
        "example_sentence": "授業が始まります。",
        "example_translation": "Class begins.",
    },
    {
        "term": "箱",
        "reading": "はこ",
        "meaning": "box",
        "level": "N5",
        "example_sentence": "箱の中に本があります。",
        "example_translation": "There are books in the box.",
    },
    {
        "term": "半分",
        "reading": "はんぶん",
        "meaning": "half",
        "level": "N5",
        "example_sentence": "りんごを半分に切ります。",
        "example_translation": "I cut the apple in half.",
    },
    {
        "term": "花",
        "reading": "はな",
        "meaning": "flower",
        "level": "N5",
        "example_sentence": "庭に花があります。",
        "example_translation": "There are flowers in the garden.",
    },
    {
        "term": "鼻",
        "reading": "はな",
        "meaning": "nose",
        "level": "N5",
        "example_sentence": "犬の鼻は大きいです。",
        "example_translation": "The dog's nose is big.",
    },
    {
        "term": "話す",
        "reading": "はなす",
        "meaning": "to speak",
        "level": "N5",
        "example_sentence": "日本語を話します。",
        "example_translation": "I speak Japanese.",
    },
    {
        "term": "晴れ",
        "reading": "はれ",
        "meaning": "clear weather",
        "level": "N5",
        "example_sentence": "今日は晴れです。",
        "example_translation": "Today is clear/sunny.",
    },
    {
        "term": "春",
        "reading": "はる",
        "meaning": "spring",
        "level": "N5",
        "example_sentence": "春は暖かいです。",
        "example_translation": "Spring is warm.",
    },
    {
        "term": "橋",
        "reading": "はし",
        "meaning": "bridge",
        "level": "N5",
        "example_sentence": "橋を渡ります。",
        "example_translation": "I cross the bridge.",
    },
    {
        "term": "箸",
        "reading": "はし",
        "meaning": "chopsticks",
        "level": "N5",
        "example_sentence": "箸で食べます。",
        "example_translation": "I eat with chopsticks.",
    },
    {
        "term": "走る",
        "reading": "はしる",
        "meaning": "to run",
        "level": "N5",
        "example_sentence": "毎朝走ります。",
        "example_translation": "I run every morning.",
    },
    {
        "term": "働く",
        "reading": "はたらく",
        "meaning": "to work",
        "level": "N5",
        "example_sentence": "会社で働きます。",
        "example_translation": "I work at a company.",
    },
    {
        "term": "速い",
        "reading": "はやい",
        "meaning": "fast (speed)",
        "level": "N5",
        "example_sentence": "この電車は速いです。",
        "example_translation": "This train is fast.",
    },
    {
        "term": "早い",
        "reading": "はやい",
        "meaning": "early",
        "level": "N5",
        "example_sentence": "朝は早いです。",
        "example_translation": "The morning is early.",
    },
    {
        "term": "低い",
        "reading": "ひくい",
        "meaning": "low, short",
        "level": "N5",
        "example_sentence": "この机は低いです。",
        "example_translation": "This desk is low.",
    },
    {
        "term": "暇",
        "reading": "ひま",
        "meaning": "free time",
        "level": "N5",
        "example_sentence": "今日は暇です。",
        "example_translation": "I am free today.",
    },
    {
        "term": "広い",
        "reading": "ひろい",
        "meaning": "spacious",
        "level": "N5",
        "example_sentence": "この公園は広いです。",
        "example_translation": "This park is spacious.",
    },
    {
        "term": "昼ご飯",
        "reading": "ひるごはん",
        "meaning": "lunch",
        "level": "N5",
        "example_sentence": "昼ご飯を食べました。",
        "example_translation": "I ate lunch.",
    },
    {
        "term": "二人",
        "reading": "ふたり",
        "meaning": "two people",
        "level": "N5",
        "example_sentence": "二人で映画を見ます。",
        "example_translation": "The two of us watch a movie.",
    },
    {
        "term": "欲しい",
        "reading": "ほしい",
        "meaning": "to want (a thing)",
        "level": "N5",
        "example_sentence": "新しいかばんが欲しいです。",
        "example_translation": "I want a new bag.",
    },
    {
        "term": "細い",
        "reading": "ほそい",
        "meaning": "thin, slender",
        "level": "N5",
        "example_sentence": "この道は細いです。",
        "example_translation": "This road is narrow.",
    },
    {
        "term": "一番",
        "reading": "いちばん",
        "meaning": "number one, the most",
        "level": "N5",
        "example_sentence": "これが一番好きです。",
        "example_translation": "I like this the most.",
    },
    {
        "term": "家",
        "reading": "いえ",
        "meaning": "house",
        "level": "N5",
        "example_sentence": "家で勉強します。",
        "example_translation": "I study at home.",
    },
    {
        "term": "池",
        "reading": "いけ",
        "meaning": "pond",
        "level": "N5",
        "example_sentence": "公園に池があります。",
        "example_translation": "There is a pond in the park.",
    },
    {
        "term": "いくら",
        "reading": "いくら",
        "meaning": "how much",
        "level": "N5",
        "example_sentence": "これはいくらですか。",
        "example_translation": "How much is this?",
    },
    {
        "term": "今",
        "reading": "いま",
        "meaning": "now",
        "level": "N5",
        "example_sentence": "今、忙しいです。",
        "example_translation": "I am busy now.",
    },
    {
        "term": "色々",
        "reading": "いろいろ",
        "meaning": "various",
        "level": "N5",
        "example_sentence": "色々な本を読みます。",
        "example_translation": "I read various books.",
    },
    {
        "term": "かばん",
        "reading": "かばん",
        "meaning": "bag",
        "level": "N5",
        "example_sentence": "かばんを買いました。",
        "example_translation": "I bought a bag.",
    },
    {
        "term": "花瓶",
        "reading": "かびん",
        "meaning": "vase",
        "level": "N5",
        "example_sentence": "花瓶に花を入れます。",
        "example_translation": "I put flowers in the vase.",
    },
    {
        "term": "階段",
        "reading": "かいだん",
        "meaning": "stairs",
        "level": "N5",
        "example_sentence": "階段を上ります。",
        "example_translation": "I go up the stairs.",
    },
    {
        "term": "会社",
        "reading": "かいしゃ",
        "meaning": "company",
        "level": "N5",
        "example_sentence": "会社に行きます。",
        "example_translation": "I go to the company (work).",
    },
    {
        "term": "紙",
        "reading": "かみ",
        "meaning": "paper",
        "level": "N5",
        "example_sentence": "紙に名前を書きます。",
        "example_translation": "I write my name on paper.",
    },
    {
        "term": "体",
        "reading": "からだ",
        "meaning": "body",
        "level": "N5",
        "example_sentence": "体が大きいです。",
        "example_translation": "My body is big.",
    },
    {
        "term": "辛い",
        "reading": "からい",
        "meaning": "spicy",
        "level": "N5",
        "example_sentence": "このカレーは辛いです。",
        "example_translation": "This curry is spicy.",
    },
    {
        "term": "カレー",
        "reading": "かれー",
        "meaning": "curry",
        "level": "N5",
        "example_sentence": "カレーを食べます。",
        "example_translation": "I eat curry.",
    },
    {
        "term": "貸す",
        "reading": "かす",
        "meaning": "to lend",
        "level": "N5",
        "example_sentence": "本を貸してください。",
        "example_translation": "Please lend me a book.",
    },
    {
        "term": "消す",
        "reading": "けす",
        "meaning": "to erase, to turn off",
        "level": "N5",
        "example_sentence": "電気を消します。",
        "example_translation": "I turn off the light.",
    },
    {
        "term": "木",
        "reading": "き",
        "meaning": "tree",
        "level": "N5",
        "example_sentence": "庭に木があります。",
        "example_translation": "There is a tree in the garden.",
    },
    {
        "term": "声",
        "reading": "こえ",
        "meaning": "voice",
        "level": "N5",
        "example_sentence": "大きい声で話します。",
        "example_translation": "I speak in a loud voice.",
    },
    {
        "term": "今朝",
        "reading": "けさ",
        "meaning": "this morning",
        "level": "N5",
        "example_sentence": "今朝は寒かったです。",
        "example_translation": "This morning was cold.",
    },
    {
        "term": "今晩",
        "reading": "こんばん",
        "meaning": "tonight",
        "level": "N5",
        "example_sentence": "今晩、勉強します。",
        "example_translation": "I will study tonight.",
    },
    {
        "term": "今月",
        "reading": "こんげつ",
        "meaning": "this month",
        "level": "N5",
        "example_sentence": "今月は忙しいです。",
        "example_translation": "This month is busy.",
    },
    {
        "term": "今週",
        "reading": "こんしゅう",
        "meaning": "this week",
        "level": "N5",
        "example_sentence": "今週は暇です。",
        "example_translation": "This week I am free.",
    },
    {
        "term": "今年",
        "reading": "ことし",
        "meaning": "this year",
        "level": "N5",
        "example_sentence": "今年、日本に行きます。",
        "example_translation": "I will go to Japan this year.",
    },
    {
        "term": "コーヒー",
        "reading": "こーひー",
        "meaning": "coffee",
        "level": "N5",
        "example_sentence": "コーヒーを飲みます。",
        "example_translation": "I drink coffee.",
    },
    {
        "term": "紅茶",
        "reading": "こうちゃ",
        "meaning": "black tea",
        "level": "N5",
        "example_sentence": "紅茶が好きです。",
        "example_translation": "I like black tea.",
    },
    {
        "term": "答える",
        "reading": "こたえる",
        "meaning": "to answer",
        "level": "N5",
        "example_sentence": "質問に答えます。",
        "example_translation": "I answer the question.",
    },
]

GRAMMAR_N5: list[dict] = [
    {
        "key": "particle-wo",
        "title": "Particle を (object marker)",
        "level": "N5",
        "explanation": "を marks the direct object of a verb.",
        "example_sentence": "水___飲みます。",
        "example_translation": "I drink water.",
        "answer": "を",
    },
    {
        "key": "particle-ga",
        "title": "Particle が (subject marker)",
        "level": "N5",
        "explanation": "が marks the grammatical subject, often introducing new information.",
        "example_sentence": "猫___います。",
        "example_translation": "There is a cat.",
        "answer": "が",
    },
    {
        "key": "particle-ni",
        "title": "Particle に (direction/time marker)",
        "level": "N5",
        "explanation": "に marks a destination, a point in time, or an indirect object.",
        "example_sentence": "学校___行きます。",
        "example_translation": "I go to school.",
        "answer": "に",
    },
    {
        "key": "particle-de",
        "title": "Particle で (location of an action)",
        "level": "N5",
        "explanation": "で marks the place where an action happens.",
        "example_sentence": "図書館___勉強します。",
        "example_translation": "I study at the library.",
        "answer": "で",
    },
    {
        "key": "particle-ha",
        "title": "Particle は (topic marker)",
        "level": "N5",
        "explanation": "は marks the topic of the sentence.",
        "example_sentence": "わたし___学生です。",
        "example_translation": "I am a student.",
        "answer": "は",
    },
    {
        "key": "past-tense-deshita",
        "title": "Past tense です → でした",
        "level": "N5",
        "explanation": "でした is the polite past tense of です.",
        "example_sentence": "昨日は晴れ___。",
        "example_translation": "It was sunny yesterday.",
        "answer": "でした",
    },
    {
        "key": "negative-verb-masen",
        "title": "Negative verb ~ません",
        "level": "N5",
        "explanation": "ません makes a polite verb negative.",
        "example_sentence": "肉を食べ___。",
        "example_translation": "I do not eat meat.",
        "answer": "ません",
    },
    {
        "key": "te-form-request",
        "title": "て-form request (~てください)",
        "level": "N5",
        "explanation": "てください is used to politely ask someone to do something.",
        "example_sentence": "ここに座っ___ください。",
        "example_translation": "Please sit here.",
        "answer": "て",
    },
    {
        "key": "particle-mo",
        "title": "Particle も (also, too)",
        "level": "N5",
        "explanation": "も replaces は/が to mean 'also' or 'too'.",
        "example_sentence": "私___学生です。",
        "example_translation": "I am also a student.",
        "answer": "も",
    },
    {
        "key": "particle-to",
        "title": "Particle と (and, with)",
        "level": "N5",
        "explanation": "と connects nouns ('and') or marks who an action is done with.",
        "example_sentence": "友達___公園に行きます。",
        "example_translation": "I go to the park with my friend.",
        "answer": "と",
    },
    {
        "key": "kara-because",
        "title": "から (because, since)",
        "level": "N5",
        "explanation": "から attaches to a plain-form clause to give a reason.",
        "example_sentence": "疲れた___、早く寝ます。",
        "example_translation": "Because I'm tired, I'll sleep early.",
        "answer": "から",
    },
    {
        "key": "made-until",
        "title": "まで (until)",
        "level": "N5",
        "explanation": "まで marks the end point of a time or place.",
        "example_sentence": "九時___働きます。",
        "example_translation": "I work until nine o'clock.",
        "answer": "まで",
    },
    {
        "key": "particle-ya",
        "title": "Particle や (and, among other things)",
        "level": "N5",
        "explanation": (
            "や lists a few examples from a longer, unstated list "
            "(unlike と, which lists everything)."
        ),
        "example_sentence": "机の上に本___ノートがあります。",
        "example_translation": "There are things like books and notebooks on the desk.",
        "answer": "や",
    },
    {
        "key": "particle-ka-question",
        "title": "Particle か (question marker)",
        "level": "N5",
        "explanation": "か at the end of a sentence turns it into a question.",
        "example_sentence": "これはあなたの傘です___。",
        "example_translation": "Is this your umbrella?",
        "answer": "か",
    },
    {
        "key": "invitation-masenka",
        "title": "~ませんか (won't you...?)",
        "level": "N5",
        "explanation": "~ませんか politely invites someone to do something together.",
        "example_sentence": "一緒に映画を見___。",
        "example_translation": "Won't you watch a movie together?",
        "answer": "ませんか",
    },
    {
        "key": "lets-mashou",
        "title": "~ましょう (let's...)",
        "level": "N5",
        "explanation": "~ましょう proposes doing something together.",
        "example_sentence": "そろそろ帰り___。",
        "example_translation": "Let's go home soon.",
        "answer": "ましょう",
    },
    {
        "key": "te-form-permission",
        "title": "~てもいいですか (may I...?)",
        "level": "N5",
        "explanation": "~てもいいですか asks for permission to do something.",
        "example_sentence": "ここに座っ___か。",
        "example_translation": "May I sit here?",
        "answer": "てもいいです",
    },
    {
        "key": "te-form-prohibition",
        "title": "~てはいけません (must not)",
        "level": "N5",
        "explanation": "~てはいけません states that an action is forbidden.",
        "example_sentence": "ここで写真を撮っ___。",
        "example_translation": "You must not take photos here.",
        "answer": "てはいけません",
    },
    {
        "key": "naide-kudasai",
        "title": "~ないでください (please don't)",
        "level": "N5",
        "explanation": "~ないでください politely asks someone not to do something.",
        "example_sentence": "教室で食べ___。",
        "example_translation": "Please don't eat in the classroom.",
        "answer": "ないでください",
    },
    {
        "key": "verb-tai",
        "title": "~たい (want to)",
        "level": "N5",
        "explanation": (
            "~たい attaches to a verb's stem to express the speaker's own desire to do it."
        ),
        "example_sentence": "日本に行き___です。",
        "example_translation": "I want to go to Japan.",
        "answer": "たい",
    },
    {
        "key": "te-form-progressive",
        "title": "~ています (ongoing action)",
        "level": "N5",
        "explanation": "~ています describes an action in progress right now.",
        "example_sentence": "今、雨が降っ___。",
        "example_translation": "It is raining now.",
        "answer": "ています",
    },
    {
        "key": "te-form-after",
        "title": "~てから (after doing)",
        "level": "N5",
        "explanation": (
            "~てから sequences two actions: the first finishes before the second starts."
        ),
        "example_sentence": "手を洗っ___、食べます。",
        "example_translation": "After washing my hands, I eat.",
        "answer": "てから",
    },
    {
        "key": "ta-koto-ga-aru",
        "title": "~たことがあります (have done before)",
        "level": "N5",
        "explanation": "~たことがあります describes a past experience.",
        "example_sentence": "沖縄へ行っ___。",
        "example_translation": "I have been to Okinawa before.",
        "answer": "たことがあります",
    },
    {
        "key": "node-because",
        "title": "ので (because, since)",
        "level": "N5",
        "explanation": "ので gives a reason, softer and more objective-sounding than から.",
        "example_sentence": "頭が痛い___、休みます。",
        "example_translation": "Because I have a headache, I'll rest.",
        "answer": "ので",
    },
    {
        "key": "verb-sugiru",
        "title": "~すぎる (too much)",
        "level": "N5",
        "explanation": "~すぎる attaches to a verb/adjective stem to mean 'excessively'.",
        "example_sentence": "このコーヒーは熱___。",
        "example_translation": "This coffee is too hot.",
        "answer": "すぎます",
    },
    {
        "key": "deshou-probably",
        "title": "~でしょう (probably)",
        "level": "N5",
        "explanation": "~でしょう softens a statement into a probable guess.",
        "example_sentence": "明日は晴れる___。",
        "example_translation": "It will probably be sunny tomorrow.",
        "answer": "でしょう",
    },
    {
        "key": "ndesu-explanatory",
        "title": "~んですか (explanatory question)",
        "level": "N5",
        "explanation": "~んですか asks for an explanation or shows the speaker noticed something.",
        "example_sentence": "どうして遅れた___か。",
        "example_translation": "Why are you late?",
        "answer": "んです",
    },
    {
        "key": "tsumori-intend",
        "title": "~つもりです (intend to)",
        "level": "N5",
        "explanation": "~つもりです states a plan or intention.",
        "example_sentence": "来年、留学する___です。",
        "example_translation": "I intend to study abroad next year.",
        "answer": "つもり",
    },
    {
        "key": "hou-ga-ii",
        "title": "~ほうがいいです (had better)",
        "level": "N5",
        "explanation": "~ほうがいいです gives advice, usually after a plain-past verb.",
        "example_sentence": "早く病院へ行った___です。",
        "example_translation": "You had better go to the hospital soon.",
        "answer": "ほうがいい",
    },
    {
        "key": "naku-temo-ii",
        "title": "~なくてもいいです (don't have to)",
        "level": "N5",
        "explanation": "~なくてもいいです says an action isn't necessary.",
        "example_sentence": "明日は仕事に行か___です。",
        "example_translation": "I don't have to go to work tomorrow.",
        "answer": "なくてもいい",
    },
    {
        "key": "nakereba-naranai",
        "title": "~なければなりません (must)",
        "level": "N5",
        "explanation": "~なければなりません states an obligation.",
        "example_sentence": "宿題をし___。",
        "example_translation": "I must do my homework.",
        "answer": "なければなりません",
    },
    {
        "key": "hoshii-want",
        "title": "~がほしいです (want something)",
        "level": "N5",
        "explanation": "ほしい is an い-adjective expressing a desire for a thing (not an action).",
        "example_sentence": "新しい靴が___です。",
        "example_translation": "I want new shoes.",
        "answer": "ほしい",
    },
    {
        "key": "yori-comparison",
        "title": "AはBより (A is more ~ than B)",
        "level": "N5",
        "explanation": "より marks the thing being compared against.",
        "example_sentence": "新幹線は電車___速いです。",
        "example_translation": "The shinkansen is faster than the train.",
        "answer": "より",
    },
    {
        "key": "ichiban-most",
        "title": "~の中で一番 (the most, out of a group)",
        "level": "N5",
        "explanation": "一番 means 'most/best' when comparing within a group introduced by の中で.",
        "example_sentence": "果物の中で、りんごが___好きです。",
        "example_translation": "Among fruits, I like apples the most.",
        "answer": "一番",
    },
    {
        "key": "ni-suru-decide",
        "title": "~にします (decide on)",
        "level": "N5",
        "explanation": "~にします states a choice/decision among options.",
        "example_sentence": "飲み物はコーヒーに___。",
        "example_translation": "I'll have coffee for my drink.",
        "answer": "します",
    },
    {
        "key": "ni-iku-purpose",
        "title": "~に行きます (go in order to)",
        "level": "N5",
        "explanation": "A verb stem + に行きます expresses going somewhere to do that action.",
        "example_sentence": "映画を見に___。",
        "example_translation": "I'm going to see a movie.",
        "answer": "行きます",
    },
    {
        "key": "no-ga-suki",
        "title": "~のが好きです (like doing)",
        "level": "N5",
        "explanation": "の turns a verb phrase into a noun so 好き/上手/下手 can describe it.",
        "example_sentence": "私は歌う___好きです。",
        "example_translation": "I like singing.",
        "answer": "の",
    },
    {
        "key": "ni-naru-become",
        "title": "~になりました (became)",
        "level": "N5",
        "explanation": "な-adjective/noun + になる describes a change of state.",
        "example_sentence": "日本語が上手___。",
        "example_translation": "My Japanese became skillful.",
        "answer": "になりました",
    },
]
