"""Small, original starter content for Phase 3 (Core Learning).

Deliberately not a full JLPT content library — just enough N5 vocabulary and
grammar to exercise flashcards, multiple choice, and sentence completion.
Broader per-level coverage (N5-N1) is Phase 13's job.
"""

VOCABULARY_N5: list[dict] = [
    {
        "term": "食べる",
        "reading": "たべる",
        "meaning": "to eat",
        "level": "N5",
        "example_sentence": "朝ごはんを食べます。",
        "example_translation": "I eat breakfast.",
    },
    {
        "term": "飲む",
        "reading": "のむ",
        "meaning": "to drink",
        "level": "N5",
        "example_sentence": "水を飲みます。",
        "example_translation": "I drink water.",
    },
    {
        "term": "見る",
        "reading": "みる",
        "meaning": "to see, to watch",
        "level": "N5",
        "example_sentence": "テレビを見ます。",
        "example_translation": "I watch TV.",
    },
    {
        "term": "行く",
        "reading": "いく",
        "meaning": "to go",
        "level": "N5",
        "example_sentence": "学校に行きます。",
        "example_translation": "I go to school.",
    },
    {
        "term": "来る",
        "reading": "くる",
        "meaning": "to come",
        "level": "N5",
        "example_sentence": "友達が来ます。",
        "example_translation": "My friend is coming.",
    },
    {
        "term": "する",
        "reading": "する",
        "meaning": "to do",
        "level": "N5",
        "example_sentence": "勉強をします。",
        "example_translation": "I study.",
    },
    {
        "term": "大きい",
        "reading": "おおきい",
        "meaning": "big",
        "level": "N5",
        "example_sentence": "大きい犬です。",
        "example_translation": "It is a big dog.",
    },
    {
        "term": "小さい",
        "reading": "ちいさい",
        "meaning": "small",
        "level": "N5",
        "example_sentence": "小さい部屋です。",
        "example_translation": "It is a small room.",
    },
    {
        "term": "学校",
        "reading": "がっこう",
        "meaning": "school",
        "level": "N5",
        "example_sentence": "学校は九時からです。",
        "example_translation": "School starts at nine.",
    },
    {
        "term": "友達",
        "reading": "ともだち",
        "meaning": "friend",
        "level": "N5",
        "example_sentence": "友達と話します。",
        "example_translation": "I talk with my friend.",
    },
    {
        "term": "水",
        "reading": "みず",
        "meaning": "water",
        "level": "N5",
        "example_sentence": "水がほしいです。",
        "example_translation": "I want water.",
    },
    {
        "term": "本",
        "reading": "ほん",
        "meaning": "book",
        "level": "N5",
        "example_sentence": "本を読みます。",
        "example_translation": "I read a book.",
    },
]

GRAMMAR_N5: list[dict] = [
    {
        "key": "particle-wo",
        "title": "Particle を (object marker)",
        "level": "N5",
        "explanation": "を marks the direct object of a verb.",
        "example_sentence": "水___飲みます。",
        "example_translation": "I drink water.",
        "answer": "を",
    },
    {
        "key": "particle-ga",
        "title": "Particle が (subject marker)",
        "level": "N5",
        "explanation": "が marks the grammatical subject, often introducing new information.",
        "example_sentence": "猫___います。",
        "example_translation": "There is a cat.",
        "answer": "が",
    },
    {
        "key": "particle-ni",
        "title": "Particle に (direction/time marker)",
        "level": "N5",
        "explanation": "に marks a destination, a point in time, or an indirect object.",
        "example_sentence": "学校___行きます。",
        "example_translation": "I go to school.",
        "answer": "に",
    },
    {
        "key": "particle-de",
        "title": "Particle で (location of an action)",
        "level": "N5",
        "explanation": "で marks the place where an action happens.",
        "example_sentence": "図書館___勉強します。",
        "example_translation": "I study at the library.",
        "answer": "で",
    },
    {
        "key": "particle-ha",
        "title": "Particle は (topic marker)",
        "level": "N5",
        "explanation": "は marks the topic of the sentence.",
        "example_sentence": "わたし___学生です。",
        "example_translation": "I am a student.",
        "answer": "は",
    },
    {
        "key": "past-tense-deshita",
        "title": "Past tense です → でした",
        "level": "N5",
        "explanation": "でした is the polite past tense of です.",
        "example_sentence": "昨日は晴れ___。",
        "example_translation": "It was sunny yesterday.",
        "answer": "でした",
    },
    {
        "key": "negative-verb-masen",
        "title": "Negative verb ~ません",
        "level": "N5",
        "explanation": "ません makes a polite verb negative.",
        "example_sentence": "肉を食べ___。",
        "example_translation": "I do not eat meat.",
        "answer": "ません",
    },
    {
        "key": "te-form-request",
        "title": "て-form request (~てください)",
        "level": "N5",
        "explanation": "てください is used to politely ask someone to do something.",
        "example_sentence": "ここに座っ___ください。",
        "example_translation": "Please sit here.",
        "answer": "て",
    },
]
